#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build Test-Upload-Release

on: 
#  release:
#    types: [published]
  push:
    branches: 
      - master
    paths:
      - 'LICENSE1'
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        mkdir -p /usr/share/artifact
        filename=test-`date +%Y-%m-%d-%s`.bin
        echo filename is : $filename
        echo "::set-env name=FILENAME::$filename"
        dd if=/dev/zero of=/usr/share/artifact/$filename bs=1M count=1
        df -h
        pwd

    - name: Upload to artifact
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Test-artifact
        path: /usr/share/artifact

    - name: Upload Release Asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: /usr/share/artifact/${{ env.FILENAME }}
        asset_name: ${{ env.FILENAME }}
        asset_content_type: application/octet-stream
